/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
// Generated by:
//
// operator-sdk create webhook --group heat --version v1beta1 --kind Heat --programmatic-validation --defaulting
//

package v1beta1

import (
	"fmt"

	topologyv1 "github.com/openstack-k8s-operators/infra-operator/apis/topology/v1beta1"
	"github.com/openstack-k8s-operators/lib-common/modules/common/service"
	common_webhook "github.com/openstack-k8s-operators/lib-common/modules/common/webhook"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/util/validation/field"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
)

// HeatDefaults -
type HeatDefaults struct {
	APIContainerImageURL    string
	CfnAPIContainerImageURL string
	EngineContainerImageURL string
	DBPurgeAge              int
	DBPurgeSchedule         string
}

var heatDefaults HeatDefaults

// log is for logging in this package.
var heatlog = logf.Log.WithName("heat-resource")

// SetupHeatDefaults - initialize Heat spec defaults for use with either internal or external webhooks
func SetupHeatDefaults(defaults HeatDefaults) {
	heatDefaults = defaults
	heatlog.Info("Heat defaults initialized", "defaults", defaults)
}

var _ webhook.Defaulter = &Heat{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *Heat) Default() {
	heatlog.Info("default", "name", r.Name)

	r.Spec.Default()
}

// Default - set defaults for this Heat spec
func (spec *HeatSpec) Default() {
	spec.HeatSpecBase.Default()
	if spec.HeatAPI.ContainerImage == "" {
		spec.HeatAPI.ContainerImage = heatDefaults.APIContainerImageURL
	}
	if spec.HeatCfnAPI.ContainerImage == "" {
		spec.HeatCfnAPI.ContainerImage = heatDefaults.CfnAPIContainerImageURL
	}
	if spec.HeatEngine.ContainerImage == "" {
		spec.HeatEngine.ContainerImage = heatDefaults.EngineContainerImageURL
	}
}

// Default - set defaults for this HeatSpecBase
func (spec *HeatSpecBase) Default() {
	// Default MessagingBus.Cluster if not set
	// Migration from deprecated fields is handled by openstack-operator
	if spec.MessagingBus.Cluster == "" {
		spec.MessagingBus.Cluster = "rabbitmq"
	}

	// NotificationsBus.Cluster is not defaulted - it must be explicitly set if NotificationsBus is configured
	// This ensures users make a conscious choice about which cluster to use for notifications

	// Default DBPurge parameters
	if spec.DBPurge.Age == 0 {
		spec.DBPurge.Age = heatDefaults.DBPurgeAge
	}
	if spec.DBPurge.Schedule == "" {
		spec.DBPurge.Schedule = heatDefaults.DBPurgeSchedule
	}
}

// getDeprecatedFields returns the centralized list of deprecated fields for HeatSpecBase
func (spec *HeatSpecBase) getDeprecatedFields(old *HeatSpecBase) []common_webhook.DeprecatedFieldUpdate {
	deprecatedFields := []common_webhook.DeprecatedFieldUpdate{
		{
			DeprecatedFieldName: "rabbitMqClusterName",
			NewFieldPath:        []string{"messagingBus", "cluster"},
			NewDeprecatedValue:  &spec.RabbitMqClusterName,
			NewValue:            &spec.MessagingBus.Cluster,
		},
	}

	// If old spec is provided (UPDATE operation), add old values
	if old != nil {
		deprecatedFields[0].OldDeprecatedValue = &old.RabbitMqClusterName
	}

	return deprecatedFields
}

// validateDeprecatedFieldsCreate validates deprecated fields during CREATE operations
func (spec *HeatSpecBase) validateDeprecatedFieldsCreate(basePath *field.Path) ([]string, field.ErrorList) {
	// Get deprecated fields list (without old values for CREATE)
	deprecatedFieldsUpdate := spec.getDeprecatedFields(nil)

	// Convert to DeprecatedField list for CREATE validation
	deprecatedFields := make([]common_webhook.DeprecatedField, len(deprecatedFieldsUpdate))
	for i, df := range deprecatedFieldsUpdate {
		deprecatedFields[i] = common_webhook.DeprecatedField{
			DeprecatedFieldName: df.DeprecatedFieldName,
			NewFieldPath:        df.NewFieldPath,
			DeprecatedValue:     df.NewDeprecatedValue,
			NewValue:            df.NewValue,
		}
	}

	return common_webhook.ValidateDeprecatedFieldsCreate(deprecatedFields, basePath), nil
}

// validateDeprecatedFieldsUpdate validates deprecated fields during UPDATE operations
func (spec *HeatSpecBase) validateDeprecatedFieldsUpdate(old HeatSpecBase, basePath *field.Path) ([]string, field.ErrorList) {
	// Get deprecated fields list with old values
	deprecatedFields := spec.getDeprecatedFields(&old)
	return common_webhook.ValidateDeprecatedFieldsUpdate(deprecatedFields, basePath)
}

// Default - set defaults for this Heat spec core. This version is called
// by the OpenStackControlplane
func (spec *HeatSpecCore) Default() {
	spec.HeatSpecBase.Default()
}

var _ webhook.Validator = &Heat{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *Heat) ValidateCreate() (admission.Warnings, error) {
	heatlog.Info("validate create", "name", r.Name)

	var allWarns []string
	var allErrs field.ErrorList
	basePath := field.NewPath("spec")

	warns, errs := r.Spec.ValidateCreate(basePath, r.Namespace)
	allWarns = append(allWarns, warns...)
	allErrs = append(allErrs, errs...)

	if len(allErrs) != 0 {
		return allWarns, apierrors.NewInvalid(
			schema.GroupKind{Group: "heat.openstack.org", Kind: "Heat"},
			r.Name, allErrs)
	}

	return allWarns, nil
}

// ValidateCreate - Exported function wrapping non-exported validate functions,
// this function can be called externally to validate an heat spec.
func (r *HeatSpec) ValidateCreate(basePath *field.Path, namespace string) ([]string, field.ErrorList) {
	var allErrs field.ErrorList
	var allWarns []string

	// Validate deprecated fields
	if warns, err := r.HeatSpecBase.validateDeprecatedFieldsCreate(basePath); err != nil {
		allWarns = append(allWarns, warns...)
		allErrs = append(allErrs, err...)
	}

	// validate the service override key is valid
	allErrs = append(allErrs, service.ValidateRoutedOverrides(
		basePath.Child("heatAPI").Child("override").Child("service"),
		r.HeatAPI.Override.Service)...)

	// validate the service override key is valid
	allErrs = append(allErrs, service.ValidateRoutedOverrides(
		basePath.Child("heatCfnAPI").Child("override").Child("service"),
		r.HeatCfnAPI.Override.Service)...)

	allErrs = append(allErrs, r.ValidateHeatTopology(basePath, namespace)...)

	return allWarns, allErrs
}

func (r *HeatSpecCore) ValidateCreate(basePath *field.Path, namespace string) ([]string, field.ErrorList) {
	var allErrs field.ErrorList
	var allWarns []string

	// Validate deprecated fields
	if warns, err := r.HeatSpecBase.validateDeprecatedFieldsCreate(basePath); err != nil {
		allWarns = append(allWarns, warns...)
		allErrs = append(allErrs, err...)
	}

	// validate the service override key is valid
	allErrs = append(allErrs, service.ValidateRoutedOverrides(
		basePath.Child("heatAPI").Child("override").Child("service"),
		r.HeatAPI.Override.Service)...)

	// validate the service override key is valid
	allErrs = append(allErrs, service.ValidateRoutedOverrides(
		basePath.Child("heatCfnAPI").Child("override").Child("service"),
		r.HeatCfnAPI.Override.Service)...)

	allErrs = append(allErrs, r.ValidateHeatTopology(basePath, namespace)...)

	return allWarns, allErrs
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *Heat) ValidateUpdate(old runtime.Object) (admission.Warnings, error) {
	heatlog.Info("validate update", "name", r.Name)
	oldHeat, ok := old.(*Heat)
	if !ok {
		return nil, apierrors.NewInternalError(
			fmt.Errorf("expected a Heatv1 object, but got %T", oldHeat))
	}

	var allWarns []string
	var allErrs field.ErrorList
	basePath := field.NewPath("spec")
	annotations := r.GetAnnotations()

	warns, errs := r.Spec.ValidateUpdate(oldHeat.Spec, basePath, annotations, r.Namespace)
	allWarns = append(allWarns, warns...)
	allErrs = append(allErrs, errs...)

	if len(allErrs) != 0 {
		return allWarns, apierrors.NewInvalid(
			schema.GroupKind{Group: "heat.openstack.org", Kind: "Heat"},
			r.Name, allErrs)
	}

	return allWarns, nil
}

// ValidateUpdate - Exported function wrapping non-exported validate functions,
// this function can be called externally to validate Heat spec.
func (r *HeatSpec) ValidateUpdate(old HeatSpec, basePath *field.Path, annotations map[string]string, namespace string) ([]string, field.ErrorList) {
	var allErrs field.ErrorList
	var allWarns []string

	// Validate deprecated fields using reflection
	if warns, err := r.HeatSpecBase.validateDeprecatedFieldsUpdate(old.HeatSpecBase, basePath); err != nil {
		allWarns = append(allWarns, warns...)
		allErrs = append(allErrs, err...)
	}

	// Allow users to bypass this validation in cases where they have independently verified
	// the validity of their new database to ensure consistency with the current one.
	if _, ok := annotations[HeatDatabaseMigrationAnnotation]; !ok {
		// We currently have no logic in place to perform database migrations. Changing databases
		// would render all of the existing stacks unmanageable. We should block changes to the
		// databaseInstance to protect existing workloads.
		if old.DatabaseInstance != "" && r.DatabaseInstance != old.DatabaseInstance {
			allErrs = append(allErrs, field.Forbidden(
				field.NewPath("spec.databaseInstance"),
				"Changing the DatabaseInstance is not supported for existing deployments"))
		}
	}

	// validate the service override key is valid
	allErrs = append(allErrs, service.ValidateRoutedOverrides(
		basePath.Child("heatAPI").Child("override").Child("service"),
		r.HeatAPI.Override.Service)...)

	// validate the service override key is valid
	allErrs = append(allErrs, service.ValidateRoutedOverrides(
		basePath.Child("heatCfnAPI").Child("override").Child("service"),
		r.HeatCfnAPI.Override.Service)...)

	allErrs = append(allErrs, r.ValidateHeatTopology(basePath, namespace)...)
	return allWarns, allErrs
}

func (r *HeatSpecCore) ValidateUpdate(old HeatSpecCore, basePath *field.Path, namespace string) ([]string, field.ErrorList) {
	var allErrs field.ErrorList
	var allWarns []string

	// Validate deprecated fields using reflection
	if warns, err := r.HeatSpecBase.validateDeprecatedFieldsUpdate(old.HeatSpecBase, basePath); err != nil {
		allWarns = append(allWarns, warns...)
		allErrs = append(allErrs, err...)
	}

	// We currently have no logic in place to perform database migrations. Changing databases
	// would render all of the existing stacks unmanageable. We should block changes to the
	// databaseInstance to protect existing workloads.
	if old.DatabaseInstance != "" && r.DatabaseInstance != old.DatabaseInstance {
		allErrs = append(allErrs, field.Forbidden(
			field.NewPath("spec.databaseInstance"),
			"Changing the DatabaseInstance is not supported for existing deployments"))
	}

	// validate the service override key is valid
	allErrs = append(allErrs, service.ValidateRoutedOverrides(
		basePath.Child("heatAPI").Child("override").Child("service"),
		r.HeatAPI.Override.Service)...)

	// validate the service override key is valid
	allErrs = append(allErrs, service.ValidateRoutedOverrides(
		basePath.Child("heatCfnAPI").Child("override").Child("service"),
		r.HeatCfnAPI.Override.Service)...)

	allErrs = append(allErrs, r.ValidateHeatTopology(basePath, namespace)...)
	return allWarns, allErrs
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *Heat) ValidateDelete() (admission.Warnings, error) {
	heatlog.Info("validate delete", "name", r.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil, nil
}

// SetDefaultRouteAnnotations sets HAProxy timeout values of the route
// NOTE: it is used by ctlplane webhook on openstack-operator
func (spec *HeatSpecCore) SetDefaultRouteAnnotations(annotations map[string]string) {
	const haProxyAnno = "haproxy.router.openshift.io/timeout"
	// Use a custom annotation to flag when the operator has set the default HAProxy timeout
	// With the annotation func determines when to overwrite existing HAProxy timeout with the APITimeout
	const heatAnno = "api.heat.openstack.org/timeout"

	valHeat, okHeat := annotations[heatAnno]
	valHAProxy, okHAProxy := annotations[haProxyAnno]

	// Human operator set the HAProxy timeout manually
	if !okHeat && okHAProxy {
		return
	}

	// Human operator modified the HAProxy timeout manually without removing the Heat flag
	if okHeat && okHAProxy && valHeat != valHAProxy {
		delete(annotations, heatAnno)
		return
	}

	timeout := fmt.Sprintf("%ds", spec.APITimeout)
	annotations[heatAnno] = timeout
	annotations[haProxyAnno] = timeout
}

// ValidateHeatTopology - Returns an ErrorList if the Topology is referenced
// on a different namespace
func (spec *HeatSpecCore) ValidateHeatTopology(basePath *field.Path, namespace string) field.ErrorList {
	var allErrs field.ErrorList

	// When a TopologyRef CR is referenced, fail if a different Namespace is
	// referenced because is not supported
	allErrs = append(allErrs, topologyv1.ValidateTopologyRef(
		spec.TopologyRef, *basePath.Child("topologyRef"), namespace)...)

	// When a TopologyRef CR is referenced with an override to HeatAPI, fail
	// if a different Namespace is referenced because not supported
	apiPath := basePath.Child("heatAPI")
	allErrs = append(allErrs,
		spec.HeatAPI.ValidateTopology(apiPath, namespace)...)

	// When a TopologyRef CR is referenced with an override to HeatCFNAPI,
	// fail if a different Namespace is referenced because not supported
	cfnPath := basePath.Child("heatCfnAPI")
	allErrs = append(allErrs,
		spec.HeatCfnAPI.ValidateTopology(cfnPath, namespace)...)

	// When a TopologyRef CR is referenced with an override to an instance of
	// HeatEngine, fail if a different Namespace is referenced because not
	// supported
	engPath := basePath.Child("heatEngine")
	allErrs = append(allErrs,
		spec.HeatEngine.ValidateTopology(engPath, namespace)...)

	return allErrs
}

// ValidateHeatTopology - Returns an ErrorList if the Topology is referenced
// on a different namespace
func (spec *HeatSpec) ValidateHeatTopology(basePath *field.Path, namespace string) field.ErrorList {
	var allErrs field.ErrorList

	// When a TopologyRef CR is referenced, fail if a different Namespace is
	// referenced because is not supported
	allErrs = append(allErrs, topologyv1.ValidateTopologyRef(
		spec.TopologyRef, *basePath.Child("topologyRef"), namespace)...)

	// When a TopologyRef CR is referenced with an override to HeatAPI, fail
	// if a different Namespace is referenced because not supported
	apiPath := basePath.Child("heatAPI")
	allErrs = append(allErrs,
		spec.HeatAPI.ValidateTopology(apiPath, namespace)...)

	// When a TopologyRef CR is referenced with an override to HeatCFNAPI,
	// fail if a different Namespace is referenced because not supported
	cfnPath := basePath.Child("heatCfnAPI")
	allErrs = append(allErrs,
		spec.HeatCfnAPI.ValidateTopology(cfnPath, namespace)...)

	// When a TopologyRef CR is referenced with an override to an instance of
	// HeatEngine, fail if a different Namespace is referenced because not
	// supported
	engPath := basePath.Child("heatEngine")
	allErrs = append(allErrs,
		spec.HeatEngine.ValidateTopology(engPath, namespace)...)

	return allErrs
}
