//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	topologyv1beta1 "github.com/openstack-k8s-operators/infra-operator/apis/topology/v1beta1"
	"github.com/openstack-k8s-operators/lib-common/modules/common/condition"
	"github.com/openstack-k8s-operators/lib-common/modules/common/service"
	"github.com/openstack-k8s-operators/lib-common/modules/storage"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIOverrideSpec) DeepCopyInto(out *APIOverrideSpec) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = make(map[service.Endpoint]service.RoutedOverrideSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIOverrideSpec.
func (in *APIOverrideSpec) DeepCopy() *APIOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(APIOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSpec) DeepCopyInto(out *AuthSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSpec.
func (in *AuthSpec) DeepCopy() *AuthSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Heat) DeepCopyInto(out *Heat) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Heat.
func (in *Heat) DeepCopy() *Heat {
	if in == nil {
		return nil
	}
	out := new(Heat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Heat) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatAPI) DeepCopyInto(out *HeatAPI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatAPI.
func (in *HeatAPI) DeepCopy() *HeatAPI {
	if in == nil {
		return nil
	}
	out := new(HeatAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeatAPI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatAPIList) DeepCopyInto(out *HeatAPIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HeatAPI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatAPIList.
func (in *HeatAPIList) DeepCopy() *HeatAPIList {
	if in == nil {
		return nil
	}
	out := new(HeatAPIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeatAPIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatAPISpec) DeepCopyInto(out *HeatAPISpec) {
	*out = *in
	in.HeatTemplate.DeepCopyInto(&out.HeatTemplate)
	in.HeatAPITemplate.DeepCopyInto(&out.HeatAPITemplate)
	if in.MemcachedInstance != nil {
		in, out := &in.MemcachedInstance, &out.MemcachedInstance
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatAPISpec.
func (in *HeatAPISpec) DeepCopy() *HeatAPISpec {
	if in == nil {
		return nil
	}
	out := new(HeatAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatAPIStatus) DeepCopyInto(out *HeatAPIStatus) {
	*out = *in
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastAppliedTopology != nil {
		in, out := &in.LastAppliedTopology, &out.LastAppliedTopology
		*out = new(topologyv1beta1.TopoRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatAPIStatus.
func (in *HeatAPIStatus) DeepCopy() *HeatAPIStatus {
	if in == nil {
		return nil
	}
	out := new(HeatAPIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatAPITemplate) DeepCopyInto(out *HeatAPITemplate) {
	*out = *in
	in.HeatAPITemplateCore.DeepCopyInto(&out.HeatAPITemplateCore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatAPITemplate.
func (in *HeatAPITemplate) DeepCopy() *HeatAPITemplate {
	if in == nil {
		return nil
	}
	out := new(HeatAPITemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatAPITemplateCore) DeepCopyInto(out *HeatAPITemplateCore) {
	*out = *in
	in.Override.DeepCopyInto(&out.Override)
	in.TLS.DeepCopyInto(&out.TLS)
	in.HeatServiceTemplate.DeepCopyInto(&out.HeatServiceTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatAPITemplateCore.
func (in *HeatAPITemplateCore) DeepCopy() *HeatAPITemplateCore {
	if in == nil {
		return nil
	}
	out := new(HeatAPITemplateCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatCfnAPI) DeepCopyInto(out *HeatCfnAPI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatCfnAPI.
func (in *HeatCfnAPI) DeepCopy() *HeatCfnAPI {
	if in == nil {
		return nil
	}
	out := new(HeatCfnAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeatCfnAPI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatCfnAPIList) DeepCopyInto(out *HeatCfnAPIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HeatCfnAPI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatCfnAPIList.
func (in *HeatCfnAPIList) DeepCopy() *HeatCfnAPIList {
	if in == nil {
		return nil
	}
	out := new(HeatCfnAPIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeatCfnAPIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatCfnAPISpec) DeepCopyInto(out *HeatCfnAPISpec) {
	*out = *in
	in.HeatTemplate.DeepCopyInto(&out.HeatTemplate)
	in.HeatCfnAPITemplate.DeepCopyInto(&out.HeatCfnAPITemplate)
	if in.MemcachedInstance != nil {
		in, out := &in.MemcachedInstance, &out.MemcachedInstance
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatCfnAPISpec.
func (in *HeatCfnAPISpec) DeepCopy() *HeatCfnAPISpec {
	if in == nil {
		return nil
	}
	out := new(HeatCfnAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatCfnAPIStatus) DeepCopyInto(out *HeatCfnAPIStatus) {
	*out = *in
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastAppliedTopology != nil {
		in, out := &in.LastAppliedTopology, &out.LastAppliedTopology
		*out = new(topologyv1beta1.TopoRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatCfnAPIStatus.
func (in *HeatCfnAPIStatus) DeepCopy() *HeatCfnAPIStatus {
	if in == nil {
		return nil
	}
	out := new(HeatCfnAPIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatCfnAPITemplate) DeepCopyInto(out *HeatCfnAPITemplate) {
	*out = *in
	in.HeatCfnAPITemplateCore.DeepCopyInto(&out.HeatCfnAPITemplateCore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatCfnAPITemplate.
func (in *HeatCfnAPITemplate) DeepCopy() *HeatCfnAPITemplate {
	if in == nil {
		return nil
	}
	out := new(HeatCfnAPITemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatCfnAPITemplateCore) DeepCopyInto(out *HeatCfnAPITemplateCore) {
	*out = *in
	in.Override.DeepCopyInto(&out.Override)
	in.TLS.DeepCopyInto(&out.TLS)
	in.HeatServiceTemplate.DeepCopyInto(&out.HeatServiceTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatCfnAPITemplateCore.
func (in *HeatCfnAPITemplateCore) DeepCopy() *HeatCfnAPITemplateCore {
	if in == nil {
		return nil
	}
	out := new(HeatCfnAPITemplateCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatDefaults) DeepCopyInto(out *HeatDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatDefaults.
func (in *HeatDefaults) DeepCopy() *HeatDefaults {
	if in == nil {
		return nil
	}
	out := new(HeatDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatEngine) DeepCopyInto(out *HeatEngine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatEngine.
func (in *HeatEngine) DeepCopy() *HeatEngine {
	if in == nil {
		return nil
	}
	out := new(HeatEngine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeatEngine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatEngineList) DeepCopyInto(out *HeatEngineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HeatEngine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatEngineList.
func (in *HeatEngineList) DeepCopy() *HeatEngineList {
	if in == nil {
		return nil
	}
	out := new(HeatEngineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeatEngineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatEngineSpec) DeepCopyInto(out *HeatEngineSpec) {
	*out = *in
	out.TLS = in.TLS
	in.HeatTemplate.DeepCopyInto(&out.HeatTemplate)
	in.HeatEngineTemplate.DeepCopyInto(&out.HeatEngineTemplate)
	if in.MemcachedInstance != nil {
		in, out := &in.MemcachedInstance, &out.MemcachedInstance
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatEngineSpec.
func (in *HeatEngineSpec) DeepCopy() *HeatEngineSpec {
	if in == nil {
		return nil
	}
	out := new(HeatEngineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatEngineStatus) DeepCopyInto(out *HeatEngineStatus) {
	*out = *in
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastAppliedTopology != nil {
		in, out := &in.LastAppliedTopology, &out.LastAppliedTopology
		*out = new(topologyv1beta1.TopoRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatEngineStatus.
func (in *HeatEngineStatus) DeepCopy() *HeatEngineStatus {
	if in == nil {
		return nil
	}
	out := new(HeatEngineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatEngineTemplate) DeepCopyInto(out *HeatEngineTemplate) {
	*out = *in
	in.HeatEngineTemplateCore.DeepCopyInto(&out.HeatEngineTemplateCore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatEngineTemplate.
func (in *HeatEngineTemplate) DeepCopy() *HeatEngineTemplate {
	if in == nil {
		return nil
	}
	out := new(HeatEngineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatEngineTemplateCore) DeepCopyInto(out *HeatEngineTemplateCore) {
	*out = *in
	in.HeatServiceTemplate.DeepCopyInto(&out.HeatServiceTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatEngineTemplateCore.
func (in *HeatEngineTemplateCore) DeepCopy() *HeatEngineTemplateCore {
	if in == nil {
		return nil
	}
	out := new(HeatEngineTemplateCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatExtraVolMounts) DeepCopyInto(out *HeatExtraVolMounts) {
	*out = *in
	if in.VolMounts != nil {
		in, out := &in.VolMounts, &out.VolMounts
		*out = make([]storage.VolMounts, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatExtraVolMounts.
func (in *HeatExtraVolMounts) DeepCopy() *HeatExtraVolMounts {
	if in == nil {
		return nil
	}
	out := new(HeatExtraVolMounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatList) DeepCopyInto(out *HeatList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Heat, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatList.
func (in *HeatList) DeepCopy() *HeatList {
	if in == nil {
		return nil
	}
	out := new(HeatList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeatList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatServiceTemplate) DeepCopyInto(out *HeatServiceTemplate) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.DefaultConfigOverwrite != nil {
		in, out := &in.DefaultConfigOverwrite, &out.DefaultConfigOverwrite
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
	if in.CustomServiceConfigSecrets != nil {
		in, out := &in.CustomServiceConfigSecrets, &out.CustomServiceConfigSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.TopologyRef != nil {
		in, out := &in.TopologyRef, &out.TopologyRef
		*out = new(topologyv1beta1.TopoRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatServiceTemplate.
func (in *HeatServiceTemplate) DeepCopy() *HeatServiceTemplate {
	if in == nil {
		return nil
	}
	out := new(HeatServiceTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatSpec) DeepCopyInto(out *HeatSpec) {
	*out = *in
	in.HeatSpecBase.DeepCopyInto(&out.HeatSpecBase)
	in.HeatAPI.DeepCopyInto(&out.HeatAPI)
	in.HeatCfnAPI.DeepCopyInto(&out.HeatCfnAPI)
	in.HeatEngine.DeepCopyInto(&out.HeatEngine)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatSpec.
func (in *HeatSpec) DeepCopy() *HeatSpec {
	if in == nil {
		return nil
	}
	out := new(HeatSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatSpecBase) DeepCopyInto(out *HeatSpecBase) {
	*out = *in
	if in.CustomServiceConfigSecrets != nil {
		in, out := &in.CustomServiceConfigSecrets, &out.CustomServiceConfigSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultConfigOverwrite != nil {
		in, out := &in.DefaultConfigOverwrite, &out.DefaultConfigOverwrite
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
	in.HeatTemplate.DeepCopyInto(&out.HeatTemplate)
	if in.TopologyRef != nil {
		in, out := &in.TopologyRef, &out.TopologyRef
		*out = new(topologyv1beta1.TopoRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatSpecBase.
func (in *HeatSpecBase) DeepCopy() *HeatSpecBase {
	if in == nil {
		return nil
	}
	out := new(HeatSpecBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatSpecCore) DeepCopyInto(out *HeatSpecCore) {
	*out = *in
	in.HeatSpecBase.DeepCopyInto(&out.HeatSpecBase)
	in.HeatAPI.DeepCopyInto(&out.HeatAPI)
	in.HeatCfnAPI.DeepCopyInto(&out.HeatCfnAPI)
	in.HeatEngine.DeepCopyInto(&out.HeatEngine)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatSpecCore.
func (in *HeatSpecCore) DeepCopy() *HeatSpecCore {
	if in == nil {
		return nil
	}
	out := new(HeatSpecCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatStatus) DeepCopyInto(out *HeatStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatStatus.
func (in *HeatStatus) DeepCopy() *HeatStatus {
	if in == nil {
		return nil
	}
	out := new(HeatStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatTemplate) DeepCopyInto(out *HeatTemplate) {
	*out = *in
	out.PasswordSelectors = in.PasswordSelectors
	if in.ExtraMounts != nil {
		in, out := &in.ExtraMounts, &out.ExtraMounts
		*out = make([]HeatExtraVolMounts, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Auth = in.Auth
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatTemplate.
func (in *HeatTemplate) DeepCopy() *HeatTemplate {
	if in == nil {
		return nil
	}
	out := new(HeatTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PasswordSelector) DeepCopyInto(out *PasswordSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PasswordSelector.
func (in *PasswordSelector) DeepCopy() *PasswordSelector {
	if in == nil {
		return nil
	}
	out := new(PasswordSelector)
	in.DeepCopyInto(out)
	return out
}
